### ISSUE TITLE
Additional suggestions

### ISSUE THREAD

**Issue by beck24** [twentyfiveautumn/admin_blog#1]
Looking much better, well done!

Another suggestion - since non-admins can't have blogs, there's no sense having pages that list their non-existent blogs.  In the owner listing page, if the pageowner isn't an admin make it 404.

Group blogs: I can see two use cases here - one where admins might want to manage group blogs, and one where the group blogs are basically redundant.  Eg. for the community site I would make the group blogs redundant.  So I guess my suggestion here is for a plugin setting that can control the behavior.

If group blog is turned off it should remove the group listing page, sidebar link, and group option.

I like being on this side of plugin suggestions, so much easier :)

**Comment by twentyfiveautumn** [comment]
That all sounds good. I'll see if I can hack something together ;)
